const QUESTIONS = [
  {
    id: 1,
    prompt: 'Câu văn nào dưới đây dùng sai quan hệ từ?',
    options: [
      'Tuy trời mưa to nhưng bạn Hà vẫn đến lớp đúng giờ.',
      'Thắng gầy nhưng rất khỏe.',
      'Đất có chất dinh dưỡng vì nuôi cây lớn.',
      'Đêm càng về khuya, trăng càng sáng.',
    ],
    answer: 'C',
  },
  {
    id: 2,
    prompt: 'Câu "Bạn có thể đưa cho tôi lọ mực được không?" thuộc kiểu câu nào?',
    options: [
      'Câu cầu khiến',
      'Câu hỏi có mục đích cầu khiến',
      'Câu hỏi',
      'Câu cảm',
    ],
    answer: 'B',
  },
  {
    id: 3,
    prompt: 'Tính từ là những từ?',
    options: [
      'Chỉ sự vật, hiện tượng, người, khái niệm',
      'Chỉ hoạt động, trạng thái của sự vật',
      'Chỉ đặc điểm, tính chất của sự vật, hoạt động, trạng thái',
      'Chỉ mối quan hệ trái ngược giữa các vế trong câu',
    ],
    answer: 'C',
  },
  {
    id: 4,
    prompt: 'Câu nào sau đây không phải câu ghép?',
    options: [
      'Cánh đồng lúa quê em đang chín rộ.',
      'Mây đen kéo kín bầu trời, cơn mưa ập tới.',
      'Bố đi xa về, cả nhà vui mừng.',
      'Bầu trời đầy sao nhưng lặng gió.',
    ],
    answer: 'A',
  },
  {
    id: 5,
    prompt: 'Trong câu sau có bao nhiêu tính từ và động từ? "Ngay thềm lăng, mười tám cây vạn tuế tượng trưng cho một đoàn quân danh dự đứng trang nghiêm."',
    type: 'pair',
    labels: ['Tính từ', 'Động từ'],
    answer: ['1', '1'],
  },
  {
    id: 6,
    prompt: 'Đáp án nào chỉ toàn các động từ?',
    options: [
      'Niềm vui, tình yêu, tình thương, niềm tâm sự',
      'Vui tươi, đáng yêu, đáng thương, sự thân thương',
      'Vui chơi, yêu thương, thương yêu, tâm sự',
      'Vui tươi, niềm vui, đáng yêu, tâm sự',
    ],
    answer: 'C',
  },
  {
    id: 7,
    prompt: 'Trong các từ sau, từ nào không phải danh từ?',
    options: ['Niềm vui', 'Màu xanh', 'Nụ cười', 'Lầy lội'],
    answer: 'D',
  },
  {
    id: 8,
    prompt: 'Trong câu "Ăn xôi đậu để thi đậu" thì từ "đậu" thuộc loại từ nào?',
    options: ['Từ nhiều nghĩa', 'Từ đồng nghĩa', 'Trái nghĩa', 'Từ đồng âm'],
    answer: 'D',
  },
  {
    id: 9,
    prompt: 'Câu "Hình ảnh người dũng sĩ mặc áo giáp sắt, đội mũ sắt, cưỡi ngựa sắt, vung roi sắt, xông thẳng vào quân giặc." là câu sai vì:',
    options: ['Thiếu chủ ngữ', 'Thiếu vị ngữ', 'Thiếu trạng ngữ', 'Thiếu cả chủ ngữ và vị ngữ'],
    answer: 'B',
  },
  {
    id: 10,
    prompt: 'Câu chia theo mục đích diễn đạt gồm các loại câu nào?',
    options: [
      'Câu kể, câu đơn, câu ghép, câu hỏi',
      'Câu hỏi, câu ghép, câu khiến, câu kể',
      'Câu kể, câu hỏi, câu cảm, câu khiến',
      'Câu kể, câu cảm, câu hỏi, câu đơn',
    ],
    answer: 'C',
  },
  {
    id: 11,
    prompt: 'Dòng nào chỉ gồm các từ đồng nghĩa?',
    options: [
      'Nhân loại, nhân tài, nhân lực',
      'Nhân hậu, nhân nghĩa, nhân ái',
      'Nhân công, nhân chứng, công nhân',
      'Nhân dân, quân nhân, nhân vật',
    ],
    answer: 'B',
  },
  {
    id: 12,
    prompt: 'Nhóm từ nào đồng nghĩa với từ "hòa bình"?',
    options: [
      'Thái bình, thanh thản, lặng yên',
      'Bình yên, thái bình, hiền hòa',
      'Thái bình, bình thản, yên tĩnh',
      'Bình yên, thái bình, thanh bình',
    ],
    answer: 'D',
  },
  {
    id: 13,
    prompt: 'Trong đoạn văn: "Chiếc xe đạp màu xanh là món quà sinh nhật của tôi. Nó giúp tôi đi học đúng giờ.", từ "nó" thay thế cho:',
    options: ['Sinh nhật', 'Món quà', 'Chiếc xe đạp', 'Màu xanh'],
    answer: 'C',
  },
  {
    id: 14,
    prompt: 'Câu nào từ "chạy" mang nghĩa gốc?',
    options: [
      'Tết đến hàng bán rất chạy.',
      'Nhà nghèo, Bác phải chạy ăn từng bữa.',
      'Lớp chúng tôi tổ chức thi chạy.',
      'Đồng hồ chạy rất đúng giờ.',
    ],
    answer: 'C',
  },
  {
    id: 15,
    prompt: 'Cặp quan hệ từ trong câu "Không chỉ sáng tác nhạc, Văn Cao còn viết văn và làm thơ" biểu thị quan hệ gì?',
    options: [
      'Quan hệ nguyên nhân - kết quả',
      'Quan hệ tương phản',
      'Quan hệ điều kiện - kết quả',
      'Quan hệ tăng tiến',
    ],
    answer: 'D',
  },
  {
    id: 16,
    prompt: 'Điền vế câu thích hợp vào chỗ trống: "Trời không những mưa to..."',
    options: [
      'Nên mọi người không đi cắm trại.',
      'Mà còn kèm theo giông lốc.',
      'Thì cây cối đổ rạp.',
      'Nên rất nguy hiểm khi đi ra đường.',
    ],
    answer: 'B',
  },
  {
    id: 17,
    prompt: 'Từ "Do" biểu thị điều gì?',
    options: [
      'Biểu thị điều sắp nêu ra là nguyên nhân của sự việc không hay được nói đến.',
      'Biểu thị điều sắp nêu ra là nguyên nhân của sự việc được nói đến.',
      'Biểu thị sự tăng tiến của sự việc.',
      'Biểu thị điều sắp nêu ra là nguyên nhân dẫn đến kết quả tốt đẹp được nói đến.',
    ],
    answer: 'B',
  },
  {
    id: 18,
    prompt: 'Đại từ trong câu "Rồi chúng tôi như bị lạc vào một thế giới ve sầu và cò, vạc..." dùng để làm gì?',
    options: [
      'Được dùng để xưng hô',
      'Được dùng để hỏi',
      'Được dùng để thay thế',
      'Được dùng để chỉ số lượng',
    ],
    answer: 'A',
  },
  {
    id: 19,
    prompt: 'Động từ là gì?',
    options: [
      'Là những từ chỉ hoạt động, trạng thái của sự vật.',
      'Là những từ chỉ đặc điểm, tính cách của con người.',
      'Là những từ chỉ sự vật, hiện tượng tự nhiên, thời gian.',
      'Là những hư từ.',
    ],
    answer: 'A',
  },
  {
    id: 20,
    prompt: 'Xác định danh từ, động từ, tính từ trong câu "Nước chảy đá mòn."',
    options: [
      'Danh từ: nước, đá; Động từ: chảy; Tính từ: mòn',
      'Danh từ: chảy, đá; Động từ: mòn; Tính từ: nước',
      'Danh từ: mòn; Động từ: chảy; Tính từ: nước, đá',
      'Danh từ: chảy; Động từ: mòn; Tính từ: nước, đá',
    ],
    answer: 'A',
  },
];
